"""
Prompt Builder Module for Local LLM (Ollama + Qwen) Response Layer.

Constructs grounded system and user prompts strictly using the structured legal
report generated by the classifier, postprocessor, and JSON legal lookup.
"""

from typing import Any


def build_system_prompt() -> str:
    """Return the system prompt establishing the persona and strict grounding constraints."""
    return (
        "You are Judi, a supportive, empathetic, and knowledgeable legal advisory assistant "
        "for students, youth, and victims in India.\n\n"
        "Your task is to take a structured preliminary legal report and present it in clear, "
        "accessible, and compassionate language.\n\n"
        "STRICT LEGAL GROUNDING RULES:\n"
        "1. DO NOT invent, hallucinate, or assume any laws, IPC/IT Act/POCSO/BNS sections, "
        "legal provisions, procedural steps, phone numbers, or case laws not present in the provided report.\n"
        "2. DO NOT change or re-classify the legal category. Accept the provided classification and context as ground truth.\n"
        "3. Preserve all specific section numbers, act names, helplines, and procedural instructions exactly as provided.\n"
        "4. If a POCSO or minor warning is present, prominently highlight confidentiality and child protection safeguards.\n"
        "5. Tone: Empathetic, calm, reassuring, professional, and clear. Avoid overly dense legalese.\n\n"
        "FORMAT YOUR RESPONSE WITH CLEAN MARKDOWN SECTIONS:\n"
        "### 📋 Case Summary & Legal Context\n"
        "(Empathetic acknowledgment of the issue, clear identification of the primary category and applicable legal framework)\n\n"
        "### ⚖️ Applicable Legal Provisions\n"
        "(Explain what each provided legal section means in plain terms)\n\n"
        "### 📝 Recommended Action Steps\n"
        "(Step-by-step guidance on FIR filing, evidence preservation, and medical examination based on provided steps)\n\n"
        "### 📞 Support & Emergency Contacts\n"
        "(List relevant helplines, police cells, and legal aid contacts provided)\n\n"
        "### ⚠️ Important Advisory\n"
        "(Highlight any warnings/confidentiality notes and remind the user to consult a registered legal practitioner or authority)"
    )


def build_user_prompt(report_data: dict[str, Any]) -> str:
    """
    Build the user prompt containing the full structured legal report context.
    
    Args:
        report_data: Dictionary containing classification, context, laws, steps, resources, etc.
    """
    user_query = report_data.get("user_query", "")
    category = report_data.get("category", "unknown")
    matched_categories = report_data.get("matched_categories", [])
    context = report_data.get("context", {}) or {}
    legal_frameworks = report_data.get("legal_frameworks", []) or []
    laws = report_data.get("laws", []) or []
    steps = report_data.get("steps", []) or []
    resources = report_data.get("resources", []) or []
    case_references = report_data.get("case_references", []) or []
    warnings = report_data.get("warnings", []) or []

    # Category formatting
    cat_names = [category.replace("_", " ").title()]
    if matched_categories:
        cat_names = [c.get("category", "").replace("_", " ").title() for c in matched_categories if c.get("category")]

    # Context details
    age_indicator = context.get("age_indicator")
    authority = context.get("authority")
    medium = context.get("medium")
    discrimination_types = context.get("discrimination_types", [])
    legal_framework = context.get("legal_framework")
    location = context.get("location")

    prompt_lines = [
        "Please summarize and explain the following preliminary legal report for the user query.",
        "",
        f"USER INCIDENT DESCRIPTION: \"{user_query}\"",
        "",
        "--- STRUCTURED LEGAL REPORT DATA ---",
        f"Primary Legal Category: {', '.join(cat_names)}",
    ]

    if age_indicator:
        prompt_lines.append(f"Age Group: {age_indicator.upper()} (POCSO Protection applicable if minor)")
    if authority:
        prompt_lines.append(f"Involved Authority/Party: {authority.replace('_', ' ').title()}")
    if medium:
        prompt_lines.append(f"Incident Medium: {medium.title()}")
    if discrimination_types:
        prompt_lines.append(f"Protected Characteristics Involved: {', '.join(discrimination_types).title()}")
    if location:
        prompt_lines.append(f"Selected Jurisdiction / Location: {location.title()}")
    if legal_framework:
        prompt_lines.append(f"Primary Legal Framework: {legal_framework}")

    if legal_frameworks:
        prompt_lines.append("\nGoverning Statutory Acts & Frameworks:")
        for fw in legal_frameworks:
            prompt_lines.append(f"- {fw}")

    if laws:
        prompt_lines.append("\nApplicable Legal Provisions & Sections:")
        for law in laws:
            act = law.get("act", "")
            sec = law.get("section", "")
            title = law.get("title", "")
            desc = law.get("description", "")
            sec_str = f"Section {sec}" if sec else ""
            header = f"- {sec_str} ({act}): {title}" if sec_str or act or title else "- Legal Provision:"
            prompt_lines.append(header)
            if desc:
                prompt_lines.append(f"  Description: {desc}")

    if steps:
        prompt_lines.append("\nRecommended Procedural & Filing Steps:")
        for idx, step in enumerate(steps, start=1):
            prompt_lines.append(f"{idx}. {step}")

    if resources:
        prompt_lines.append("\nAvailable Support Helplines & Legal Aid Contacts:")
        for res in resources:
            if isinstance(res, str):
                prompt_lines.append(f"- {res}")
            elif isinstance(res, dict):
                name = res.get("name", "Resource")
                contact = res.get("contact", "")
                loc = res.get("location", "")
                link = res.get("link", "")
                desc = res.get("description", "")
                info_parts = [name]
                if loc:
                    info_parts.append(f"Location: {loc}")
                if contact:
                    info_parts.append(f"Contact: {contact}")
                if link:
                    info_parts.append(f"Link: {link}")
                if desc:
                    info_parts.append(f"Details: {desc}")
                prompt_lines.append(f"- {' | '.join(info_parts)}")

    if case_references:
        prompt_lines.append("\nRelevant Landmark Case References:")
        for case in case_references:
            prompt_lines.append(f"- {case}")

    if warnings:
        prompt_lines.append("\nImportant Advisories & Safety Warnings:")
        for warning in warnings:
            prompt_lines.append(f"- {warning}")

    prompt_lines.extend([
        "------------------------------------",
        "",
        "Instructions for final output:",
        "- Provide a cohesive, well-structured, and empathetic response explaining these specific findings.",
        "- Do not omit key sections or emergency contacts.",
        "- Do not add any laws or numbers not listed above.",
    ])

    return "\n".join(prompt_lines)


def build_prompts(report_data: dict[str, Any]) -> tuple[str, str]:
    """
    Build both system and user prompts for the local LLM.
    
    Returns:
        (system_prompt, user_prompt)
    """
    return build_system_prompt(), build_user_prompt(report_data)
